development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://red-cpfh8htds78s739cqr7g:6379" } %>
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: chatapp_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://red-cpfh8htds78s739cqr7g:6379" } %>
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: chatapp_production